"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-23 10:04:28.451619

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('elaboracio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipus', sa.Enum('semielaborat', 'producte', name='tipuselaboracio'), nullable=False),
    sa.Column('prefix_lot', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actiu', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_elaboracio_nom'), 'elaboracio', ['nom'], unique=True)
    op.create_index(op.f('ix_elaboracio_prefix_lot'), 'elaboracio', ['prefix_lot'], unique=True)
    op.create_table('ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actiu', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredient_nom'), 'ingredient', ['nom'], unique=True)
    op.create_table('proveidor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actiu', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proveidor_nom'), 'proveidor', ['nom'], unique=True)
    op.create_table('lot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipus', sa.Enum('materia_primera', 'semielaborat', 'producte', name='tipuslot'), nullable=False),
    sa.Column('codi', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('creat_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('responsable', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('observacions', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('anulat_per_id', sa.Integer(), nullable=True),
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.Column('proveidor_id', sa.Integer(), nullable=True),
    sa.Column('lot_proveidor', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('data_recepcio', sa.Date(), nullable=True),
    sa.Column('caducitat', sa.Date(), nullable=True),
    sa.Column('tipus_data', sa.Enum('caducitat', 'consum_preferent', name='tipusdata'), nullable=True),
    sa.Column('elaboracio_id', sa.Integer(), nullable=True),
    sa.Column('quantitat', sa.Float(), nullable=True),
    sa.Column('unitat', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('elaborat_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('torn', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.CheckConstraint("tipus != 'materia_primera' OR (ingredient_id IS NOT NULL AND proveidor_id IS NOT NULL AND lot_proveidor IS NOT NULL AND data_recepcio IS NOT NULL AND tipus_data IS NOT NULL)", name='ck_lot_materia_primera_camps'),
    sa.CheckConstraint("tipus = 'materia_primera' OR (elaboracio_id IS NOT NULL AND quantitat IS NOT NULL AND unitat IS NOT NULL AND elaborat_at IS NOT NULL)", name='ck_lot_elaboracio_camps'),
    sa.ForeignKeyConstraint(['anulat_per_id'], ['lot.id'], ),
    sa.ForeignKeyConstraint(['elaboracio_id'], ['elaboracio.id'], ),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.ForeignKeyConstraint(['proveidor_id'], ['proveidor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lot_codi'), 'lot', ['codi'], unique=True)
    op.create_index(op.f('ix_lot_tipus'), 'lot', ['tipus'], unique=False)
    op.create_table('recepta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('elaboracio_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.Column('semielaborat_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('(ingredient_id IS NOT NULL) != (semielaborat_id IS NOT NULL)', name='ck_recepta_un_sol_component'),
    sa.ForeignKeyConstraint(['elaboracio_id'], ['elaboracio.id'], ),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.ForeignKeyConstraint(['semielaborat_id'], ['elaboracio.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('elaboracio_id', 'ingredient_id', name='uq_recepta_elaboracio_ingredient'),
    sa.UniqueConstraint('elaboracio_id', 'semielaborat_id', name='uq_recepta_elaboracio_semielaborat')
    )
    op.create_index(op.f('ix_recepta_elaboracio_id'), 'recepta', ['elaboracio_id'], unique=False)
    op.create_table('consum',
    sa.Column('lot_produit_id', sa.Integer(), nullable=False),
    sa.Column('lot_consumit_id', sa.Integer(), nullable=False),
    sa.Column('origen', sa.Enum('automatic', 'manual', name='origenconsum'), nullable=False),
    sa.ForeignKeyConstraint(['lot_consumit_id'], ['lot.id'], ),
    sa.ForeignKeyConstraint(['lot_produit_id'], ['lot.id'], ),
    sa.PrimaryKeyConstraint('lot_produit_id', 'lot_consumit_id')
    )
    op.create_table('incidencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipus', sa.Enum('canvi_lot', 'devolucio', 'alerta', 'altra', name='tipusincidencia'), nullable=False),
    sa.Column('data_hora', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('responsable', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lot_afectat_id', sa.Integer(), nullable=False),
    sa.Column('lot_anterior_id', sa.Integer(), nullable=True),
    sa.Column('lot_nou_id', sa.Integer(), nullable=True),
    sa.Column('motiu', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mesura_adoptada', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('comprovacio', sa.Boolean(), nullable=False),
    sa.Column('comprovat_per', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('afectats_snapshot', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['lot_afectat_id'], ['lot.id'], ),
    sa.ForeignKeyConstraint(['lot_anterior_id'], ['lot.id'], ),
    sa.ForeignKeyConstraint(['lot_nou_id'], ['lot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lotenus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('inici', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('fi', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('observacions', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lotenus_ingredient_id'), 'lotenus', ['ingredient_id'], unique=False)
    # ### end Alembic commands ###

    # Solo puede haber un lote en uso (fi IS NULL) por ingredient_id.
    # Índice único parcial — sintaxis distinta en SQLite/PostgreSQL, por
    # eso se pasan ambos kwargs de dialecto (cada motor ignora el que no
    # es el suyo); no hay forma portable de expresarlo en un solo kwarg.
    op.create_index(
        'uq_lotenus_ingredient_obert',
        'lotenus',
        ['ingredient_id'],
        unique=True,
        sqlite_where=sa.text('fi IS NULL'),
        postgresql_where=sa.text('fi IS NULL'),
    )


def downgrade() -> None:
    op.drop_index('uq_lotenus_ingredient_obert', table_name='lotenus')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lotenus_ingredient_id'), table_name='lotenus')
    op.drop_table('lotenus')
    op.drop_table('incidencia')
    op.drop_table('consum')
    op.drop_index(op.f('ix_recepta_elaboracio_id'), table_name='recepta')
    op.drop_table('recepta')
    op.drop_index(op.f('ix_lot_tipus'), table_name='lot')
    op.drop_index(op.f('ix_lot_codi'), table_name='lot')
    op.drop_table('lot')
    op.drop_index(op.f('ix_proveidor_nom'), table_name='proveidor')
    op.drop_table('proveidor')
    op.drop_index(op.f('ix_ingredient_nom'), table_name='ingredient')
    op.drop_table('ingredient')
    op.drop_index(op.f('ix_elaboracio_prefix_lot'), table_name='elaboracio')
    op.drop_index(op.f('ix_elaboracio_nom'), table_name='elaboracio')
    op.drop_table('elaboracio')
    # ### end Alembic commands ###
