"""add consum anulat_at

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-23 10:25:46.954836

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consum', sa.Column('anulat_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consum', 'anulat_at')
    # ### end Alembic commands ###
