"""add client_id to lot

Revision ID: 84190338e221
Revises: 0002
Create Date: 2026-09-23 20:04:44.928724

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lot', sa.Column('client_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_lot_client_id'), 'lot', ['client_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lot_client_id'), table_name='lot')
    op.drop_column('lot', 'client_id')
    # ### end Alembic commands ###
