"""add client_id to lotenus and incidencia

Revision ID: eac60d1b5276
Revises: 0003
Create Date: 2026-09-23 20:15:50.376578

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidencia', sa.Column('client_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_incidencia_client_id'), 'incidencia', ['client_id'], unique=True)
    op.add_column('lotenus', sa.Column('client_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_lotenus_client_id'), 'lotenus', ['client_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lotenus_client_id'), table_name='lotenus')
    op.drop_column('lotenus', 'client_id')
    op.drop_index(op.f('ix_incidencia_client_id'), table_name='incidencia')
    op.drop_column('incidencia', 'client_id')
    # ### end Alembic commands ###
